version: "3.8"
services:
  # db:
  #   image: mongo:7.0.2-jammy
  #   restart: always
  #   container_name: mongo-test
  #   volumes:
  #     - ./.db:/data/db
  #   expose:
  #     - 27017
  #   ports:
  #     - 27017:27017
  # api:
  #   build:
  #     context: ./be-node
  #     dockerfile: Dockerfile
  #   container_name: node-test
  #   ports:
  #     - 5000:5000
  #   volumes:
  #     - ./be-node:/app
  #     - /app/node_modules/
  #   depends_on:
  #     - db
  # web:
  #   build: ./fe-react
  #   container_name: react-test
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./fe-react:/app
  #     - /app/node_modules/
  #   depends_on:
  #     - api
  nxt:
    build: ./next-js
    container_name: next-test
    ports:
      - 3001:3000
    volumes:
      - ./next-js:/app
      - /app/node_modules/
      - /app/.next/